import os
import json
import re
from google.cloud import storage
from collections import defaultdict

# User Settings (Match these to your batch script)
PROJECT_ID = "cat-gen-lang-proj"
BUCKET_NAME = "landmark-annotations"
GCS_OUTPUT_PREFIX = "landmark_batch_job/output/" # The prefix you used for output
LOCAL_OUT_PATH = "/home/alekseyvalouev/goalnav/"

with open("data_config.json", "r") as f:
    data_config = json.load(f)
    scenes_train = data_config["scenes_train"]
    scenes_train_dir = os.path.join(LOCAL_OUT_PATH, "language-annotations-train-new")
    scenes_test = data_config["scenes_test"]
    scenes_test_dir = os.path.join(LOCAL_OUT_PATH, "language-annotations-test-new")
    scenes_other = data_config["scenes_other"]
    scenes_other_dir = os.path.join(LOCAL_OUT_PATH, "language-annotations-other-new")

def download_and_parse_results():
    client = storage.Client(project=PROJECT_ID)
    bucket = client.bucket(BUCKET_NAME)
    
    # List all output files generated by the batch job
    # Vertex usually names them 'prediction-results-*.jsonl'
    blobs = bucket.list_blobs(prefix=GCS_OUTPUT_PREFIX)
    
    # Dictionary to aggregate results by scene: {scene_name: {image_name: [landmarks]}}
    scene_data = defaultdict(lambda: {"landmarks": {}})

    print("Downloading and processing results...")
    
    for blob in blobs:
        if not blob.name.endswith(".jsonl"):
            continue
            
        content = blob.download_as_text()
        for line in content.strip().split('\n'):
            if not line: continue
            
            data = json.loads(line)
            print(data)
            
            # 1. Extract the original GCS URI to identify the scene and image
            # The structure follows the input request you sent
            try:
                # In Vertex Batch, the original instance is returned in the 'instance' key
                parts = data['request']['contents'][0]['parts']
                image_uri = next(part['file_data']['file_uri'] for part in parts if 'file_data' in part and part['file_data'] is not None and part['file_data'] is not None)
                
                # Parse the URI: gs://bucket/path/images/{scene}/{filename}
                # Based on our previous script's upload logic:
                uri_parts = image_uri.split('/')
                image_name = uri_parts[-1]
                scene_name = uri_parts[-2]
                
                # 2. Extract the prediction
                # Response is a JSON string inside the 'text' field of the first candidate
                prediction_text = data['response']['candidates'][0]['content']['parts'][0]['text']
                prediction_json = json.loads(prediction_text)
                landmarks = prediction_json.get("landmarks", [])
                
                # 3. Add to our local aggregate
                scene_data[scene_name]["landmarks"][image_name] = landmarks
                
            except (KeyError, IndexError, StopIteration, json.JSONDecodeError) as e:
                print(f"Skipping a malformed line: {e}")

    for scene_name, content in scene_data.items():
        if scene_name in scenes_train:
            out_path = scenes_train_dir
        elif scene_name in scenes_test:
            out_path = scenes_test_dir
        elif scene_name in scenes_other:
            out_path = scenes_other_dir
        else:
            print("Scene not found in data config. Skipped.")
            continue
        
        if not os.path.exists(out_path):
            os.makedirs(out_path, exist_ok=True)
        
        output_file = os.path.join(out_path, f"{scene_name}_landmarks.json")
        with open(output_file, "w") as f:
            json.dump(content, f, indent=4)
        print(f"Reconstructed: {output_file} ({len(content['landmarks'])} images)")

if __name__ == "__main__":
    download_and_parse_results()